### ISSUE TITLE
404 not found error

### ISSUE THREAD

**Issue by partymike** [samccauley/addon-hassiogooglebackup#16]
Hi, looks like a great addon and all seem to proceed ok with install:

1. grabbed drive folder name from google (fake one below!)
2. authorized the service ok

when I test with http://192.168.10.5:8123/gb/doBackup

I get response:

HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=utf-8
Content-Length: 14
Date: Fri, 22 Mar 2019 12:52:18 GMT
Server: Python/3.7 aiohttp/3.5.4
Connection: close

404: Not Found
---
config:
{
  "fromPattern": "/backup/*.tar",
  "backupDirID": "mygooglefolderidhere",
  "purge": {
    "enabled": true,
    "preserve": 3
  },
  "purge_google": {
    "enabled": false,
    "preserve": 12
  },
  "debug": false
}
---
Log shows:

GB_DEBUG = false
INFO:root:No local_settings to import
---
Any idea?

**Comment by samccauley** [comment]
@partymike I see that you tried to use port 8123 (typically hassio port). Instead, you need to use the port number that you configured on the add-on (default is 8055).

**Comment by partymike** [comment]
apologies being a bit fick! works perfect, thank for this :-)
