### ISSUE TITLE
Using adhocBackup fails on directories - "can only concatenate str (not "NoneType") to str"

### ISSUE THREAD

**Issue by sdwilko** [samccauley/addon-hassiogooglebackup#18]
When I try to run an adhocBackup (via rest_command with correct JSON payload), I get this error in the logs (complete log pasted below).

The directory it's backing up has multiple nested sub-directories (in this case, I'm using it to backup security camera footage from my share directory). It seems to be failing on the directory, hence the empty MIMETYPE variable unable to be concat'ed - so I'm assuming directories can't be backed up? Couldn't see anything which said this was the case though, so thought I'd create an issue just in case it's something you want to address. 
I'm no python dev, but I'll take a look and maybe submit a PR as it only seems to be in the debug output...

Here's the rest command:
```
google_backup_camera:
  url: http://localhost:8055/gb/adhocBackup
  method: POST
  timeout: 300
  headers:
    accept: 'application/json, text/html'
  payload: '{"fromPatterns" : ["/share/motioneye/*"], "backupDirID" : "<REDACTED>"}'
  content_type:  'application/json; charset=utf-8'
```

And here's the full error in add-on logs:
```
INFO:oauth2client.client:Refreshing access_token
INFO:oauth2client.transport:Attempting refresh to obtain initial access_token
INFO:oauth2client.client:Refreshing access_token
WARNING:googleapiclient._helpers:build() takes at most 2 positional arguments (3 given)
INFO:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/discovery/v1/apis/drive/v3/rest
INFO:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/drive/v3/files?q=name%3D%27Front_Garden%27+and+%27<REDACTED>%27+in+parents+and+trashed+%3D+false&spaces=drive&fields=files%28id%2C+name%29&alt=json
INFO:root:Deleted 0 files named Front_Garden from Google Drive.
INFO:root:Backing up /share/motioneye/Front_Garden to <REDACTED>
ERROR:root:Traceback (most recent call last):
  File "/googlebackup/gb/views.py", line 49, in adhocBackup
    adhocBackupResult = adhocBackupFiles(fromPatterns, backupDirID, request.build_absolute_uri('/'))
  File "/googlebackup/gbcommon.py", line 225, in adhocBackupFiles
    backupFile(file, backupDirID, drive_service, MIMETYPE, TITLE, DESCRIPTION)
  File "/googlebackup/gbcommon.py", line 141, in backupFile
    logging.debug("MIMETYPE = " + MIMETYPE)
TypeError: can only concatenate str (not "NoneType") to str
INFO:root:googlebackup adhocBackup result: {'errorMessage': 'can only concatenate str (not "NoneType") to str'}
ERROR:django.request:Internal Server Error: /gb/adhocBackup
[27/Mar/2019 12:30:01] "POST /gb/adhocBackup HTTP/1.1" 500 70
```

**Comment by sdwilko** [comment]
OK so I've looked through the code and the googleapiclient library and answered my own question. 
Could use the `application/vnd.google-apps.folder` mimetype for directories, but then we'd have to check whether it already exists and if it does implement some recursion for further nested directories to get back the ID to use as parent and save files there.

Can of worms, so I'm closing for now, will look into it as soon as I have some time.

**Comment by samccauley** [comment]
@sdwilko Thanks for bringing to my attention. Honestly, I hadn't even thought of directories, let alone nested directories. I'll give this some thought. I should at least add documentation and graceful handling of the situation.
