### ISSUE TITLE
server error (500)

### ISSUE THREAD

**Issue by RaveGun** [samccauley/addon-hassiogooglebackup#19]
Hello,

I was trying to setup the plugin on my hass.io running on a RPi but I failed authorize the app.

Now I try to get my head around how this authorisation works.

Does Google need have direct access to the RPi in order to authorize this?

The RPi is just in my local network and I do not have any access to, from the outside. My entire network does not have any open ports exposed.

Is there another way to this work?

I do have setup and configured an application in the Google API that is used by the hass.io for the a calendar feature. This was also a pain to setup back then.

Is this maybe a Google temporary issue right now?

Thank you.

**Comment by samccauley** [comment]
Google does not access your RPi. The authorization process takes place entirely between your web browser and Google. Google will give you a code that you will need to copy and paste into the add-on. The add-on will save that code on your RPi and will use that code to authenticate itself to Google.

**Comment by RaveGun** [comment]
OK, thank you.

Maybe I need to try this on my computer and not from my mobile phone.

I will report back how it goes.

Thank you.

**Comment by RaveGun** [comment]
Hi,

It just does not work.
I also disabled the PiHole, I switched to CloudFlare directly.
I did not saw in the PiHole logs anything blocked from my PI IP address.
Anyhow it is not that hard to just download the file to my Drive anyway.

Thanks anyway.
