### ISSUE TITLE
Add timestamp to the returned JSON

### ISSUE THREAD

**Issue by thibmaek** [samccauley/addon-hassiogooglebackup#3]
Hi, do you think it is possible to add a timestamp to the JSON response?
This way I could create a REST sensor which runs every day, grabs the JSON response and extracts a key `lastSuccessfulBackup` and using the value_template property of the rest sensor and extracting the json it could be displayed in the Home Assistant frontend.

**Comment by samccauley** [comment]
This is done in version 1.3.0 available now.

**Comment by thibmaek** [comment]
Nice! Thank you
