### ISSUE TITLE
Purge_Google not executing

### ISSUE THREAD

**Issue by mpartoglou** [samccauley/addon-hassiogooglebackup#36]
Hi, love this add-on, have used it extensively.

I notice that it is not correctly honouring the purge_google file count. I have mine set to preserve 600 (falls nicely under my Google Drive data limit), however it doesn't execute a delete command even though it shows the file-count is >600.

Add-on Version: 1.7.6 (latest)
HassOS with latest supervisor on 113.3

Can provide more logs / details.

Config (Note: I use this to back-up my camera footage to google drive // removed backupdir details
```
fromPattern: /share/garage/*/*/*/*.mp4
backupDirID: xxxxxxxxx
purge:
  enabled: false
  preserve: 5
purge_google:
  enabled: true
  preserve: 600
debug: false

```

Log output (2x Logs from two times today)
```
INFO:root:googlebackup result: {'backupTimestamp': '2020-08-17T01:23:58.353681', 'fromPattern': '/share/garage/*/*/*/*.mp4', 'backupDirID': 'xxxxxxxxxx', 'fileCount': 673, 'alreadyCount': 615, 'backedUpCount': 58, 'deletedFromGoogle': 0}
```

```
INFO:root:googlebackup result: {'backupTimestamp': '2020-08-17T03:07:44.126802', 'fromPattern': '/share/garage/*/*/*/*.mp4', 'backupDirID': 'xxxxxxxxxx', 'fileCount': 711, 'alreadyCount': 683, 'backedUpCount': 28, 'deletedFromGoogle': 0}
```

My configuration.yaml (as relevant), this service is called daily via an automation
```
rest_command:
  google_backup:
    url: 'http://localhost:8055/gb/doBackup'
    timeout: '600'
```

**Comment by mpartoglou** [comment]
Update, ran it again with debug:true

Doesn't appear to be anything additional to help with the debug process.

```
INFO:root:Nothing to purge from Google Drive
INFO:root:googlebackup result: {'backupTimestamp': '2020-08-17T03:20:28.053047', 'fromPattern': '/share/garage/*/*/*/*.mp4', 'backupDirID': 'xxxxx', 'fileCount': 717, 'alreadyCount': 712, 'backedUpCount': 5, 'deletedFromGoogle': 0}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): hassio:80
DEBUG:urllib3.connectionpool:http://hassio:80 "POST /homeassistant/api/services/mqtt/publish HTTP/1.1" 200 2
DEBUG:root:<Response [200]>
```

**Comment by samccauley** [comment]
> Hi, love this add-on, have used it extensively.
> 
> I notice that it is not correctly honouring the purge_google file count. I have mine set to preserve 600 (falls nicely under my Google Drive data limit), however it doesn't execute a delete command even though it shows the file-count is >600.
> 
> Add-on Version: 1.7.6 (latest)
> HassOS with latest supervisor on 113.3
> 
> Can provide more logs / details.
> 
> Config (Note: I use this to back-up my camera footage to google drive // removed backupdir details
> 
> ```
> fromPattern: /share/garage/*/*/*/*.mp4
> backupDirID: xxxxxxxxx
> purge:
>   enabled: false
>   preserve: 5
> purge_google:
>   enabled: true
>   preserve: 600
> debug: false
> ```
> 
> Log output (2x Logs from two times today)
> 
> ```
> INFO:root:googlebackup result: {'backupTimestamp': '2020-08-17T01:23:58.353681', 'fromPattern': '/share/garage/*/*/*/*.mp4', 'backupDirID': 'xxxxxxxxxx', 'fileCount': 673, 'alreadyCount': 615, 'backedUpCount': 58, 'deletedFromGoogle': 0}
> ```
> 
> ```
> INFO:root:googlebackup result: {'backupTimestamp': '2020-08-17T03:07:44.126802', 'fromPattern': '/share/garage/*/*/*/*.mp4', 'backupDirID': 'xxxxxxxxxx', 'fileCount': 711, 'alreadyCount': 683, 'backedUpCount': 28, 'deletedFromGoogle': 0}
> ```
> 
> My configuration.yaml (as relevant), this service is called daily via an automation
> 
> ```
> rest_command:
>   google_backup:
>     url: 'http://localhost:8055/gb/doBackup'
>     timeout: '600'
> ```

**Comment by samccauley** [comment]
@mpartoglou  My personal use case is straight forward and works fine. So my question may seem simple. Forgive me.

Are your backed up files showing up in Google drive in nested sub folders within your designated back up folder? Mine all appear directly in my designated backup folder (no sub folders). I suspect this might be the difference that causes my code to break for you. Can you please confirm?

**Comment by mpartoglou** [comment]
Hi @samccauley , I can confirm that all files are uploaded to a single folder in google drive and appear directly in the designated folder (eg. Not nested within subfolders). 

Google_drive/designated_folder/video_1.mp4
Google_drive/designated_folder/video_2.mp4

Where designated_folder is the folder set within the configuration.

**Comment by samccauley** [comment]
@mpartoglou I found the problem. I wasn't supporting paginated results coming back from Google Drive in the case where the number of files exceeded 100. Fix will be coming shortly.

**Comment by mpartoglou** [comment]
@samccauley thanks for checking and identifying the issue. I know my use case is not intended so really appreciate the fix. I’ll test ASAP once it’s released.

**Comment by samccauley** [comment]
@mpartoglou Okay. Give version 1.7.7 a try.

**Comment by mpartoglou** [comment]
Thanks, updated and tried then, my google drive quote was exceeded. I’ll have to try a bit later when I’m back home after I delete some of the larger video files. 

Will confirm the fix shortly

**Comment by mpartoglou** [comment]
Hi @samccauley 

I can confirm it worked and i have exactly the number of files set (i.e. 600).

```
INFO:root:googlebackup result: {'backupTimestamp': '2020-08-19T23:17:19.209581', 'fromPattern': '/share/garage/*/*/*/*.mp4', 'backupDirID': '1RdOtRWAIl0MbdshFrQP5FUCjTXlJf5Cz', 'fileCount': 636, 'alreadyCount': 464, 'backedUpCount': 172, 'deletedFromGoogle': 1252}
```

Thanks for identifying and turning around a fix so quickly!!

I'll close this issue
