### ISSUE TITLE
Multiple backup patterns?

### ISSUE THREAD

**Issue by thibmaek** [samccauley/addon-hassiogooglebackup#7]
Would be useful to have multiple backup patterns so I could also backup credentials like the secrets file.

```
"fromPattern": ["/backup/*.tar", "/config/secrets.yaml", "/config/.ps4-waker-credentials.json"],
```

Could take a stab at this myself and open a PR but really busy so won't be for the following 6 months or so.

**Comment by thibmaek** [comment]
From what I figured I'd have to loop over the list in https://github.com/samccauley/addon-hassiogooglebackup/blob/a12bbef0176852d5400c66e3f8eeb0b7766fa025/hassiogooglebackup/googlebackup/gbcommon.py#L137 and then call the glob function there.

**Comment by wimpie007** [comment]
would be a very handy option indeed!!

**Comment by samccauley** [comment]
The question would be whether each pattern would require associated values for <purge> and <purge_google> in the options. Help me understand the use case and whether it would indeed require a separate purge values for each pattern.

**Comment by thibmaek** [comment]
Nah, in the example above I'd like to backup my secrets or other env data and overwrite it on Google Drive each time it backs up. These wouldn't be incremental backups but just in place backups

**Comment by thibmaek** [comment]
Nah, in the example above I'd like to backup my secrets or other env data and overwrite it on Google Drive each time it backs up. These wouldn't be incremental backups but just in place backups

**Comment by wimpie007** [comment]
and i would want to backup a certain directory "extra" to the 'normal' ones that are included in the snapshot...
Also here: no incremental needed.

**Comment by samccauley** [comment]
@thibmaek 
Following your suggestion, if someone had these patterns:
"fromPattern": ["/backup/*.tar", "/config/secrets.yaml", "/config/.ps4-waker-credentials.json"]
and they had 3 .tar files, and they had this purge setting:
"purge" : {"enabled" : true, "preserve" : 3}
...What exactly should the preserve number, 3, apply to?  How will it be obvious to the user what it applies to?

Your use case goes outside the bounds of the current design. I think to accomodate it, I would need to restructure the options like this (notice the purges are disabled on the non-tar files):

{Backups: [
  {"fromPattern" : "/backup/*.tar",
     "backupDirID" : "GDRIVE_GUID_1",
     "purge" : {"enabled" : true, "preserve" : 3},
     "purge_google" : {"enabled" : true, "preserve" : 12},
  {"fromPattern" : "/config/secrets.yaml",
     "backupDirID" : "GDRIVE_GUID_2",
     "purge" : {"enabled" : false, "preserve" : 3},
     "purge_google" : {"enabled" : false, "preserve" : 12}
  }],
  {"fromPattern" : "/config/.ps4-waker-credentials.json",
     "backupDirID" : "GDRIVE_GUID_2",
     "purge" : {"enabled" : false, "preserve" : 3},
     "purge_google" : {"enabled" : false, "preserve" : 12}
  }],
 "debug" : false
}

**Comment by thibmaek** [comment]
Or use an extra property `extraFiles` where extra files can be provided that will overwrite those on Google Drive?

**Comment by samccauley** [comment]
@thibmaek and @wimpie007  What if I created an ad-hoc backup operation that would be in addition to the current doBackup operation? Where as the doBackup operation has no arguments and relies on the configured options, the ad-hoc operation would require two arguments: fromPatterns (an array) and toDirectory. The ad-hoc operation would ignore the various configured options (except "debug") and simply copy the files matching the patterns to the identified G-drive directory.

Would that meet your needs?

**Comment by thibmaek** [comment]
That would do the trick! Best would be to copy old files on overwrite.

**Comment by wimpie007** [comment]
perfect for me too! 😁

**Comment by samccauley** [comment]
I created version 1.6.0 of my add-on that now has an additional operation called adhocBackup. This operation accepts an array of fromPatterns and a single value for backupDirID. You can read more about it in the updated readme.

There's a problem, though. I was not able to figure out how to create a Home Assistant REST Command for making this service callable via Home Assistant. My sticking point was the array of fromPatterns. I could not figure out how to define a template to support the array. I attempted to define it this way in my configuration.yaml, but it still translated the fromPatterns array as one long string instead of as an array.

rest_command:
  google_adhoc_backup:
    url: 'http://localhost:8055/gb/adhocBackup'
    method: POST
    content_type: 'application/json; charset=utf-8'
    payload: '{"fromPatterns":"{{ fromPatterns }}","backupDirID": "{{ backupDirID }}"}'
    timeout: '300'

**Comment by thibmaek** [comment]
Cool! Why would you not be able to pass an array?
![image](https://user-images.githubusercontent.com/6213695/54488765-107e6280-48a6-11e9-86d2-b46e905bb6d6.png)

**Comment by samccauley** [comment]
@thibmaek 

Yeah. I was able to do something like that in the template editor, too. But I can't seem to apply that technique to a [Rest Command](https://www.home-assistant.io/components/rest_command/). I wanted to create a Rest Command that can be invoked via the Services Developer Tool in such a way that a different list of files can be provided each time you call the service via the Services Developer Tool. I still don't understand how to do that.

**Comment by thibmaek** [comment]
Mine is working fine here with the payload in my secrets: https://github.com/thibmaek/homeassistant-conf/blob/master/components/rest_commands/hassio_google_drive.yaml

Note that I'm not using variables in my payload, just hardcoded strings.

Going to close this issue since my initial wish has been fulfilled!

**Comment by wimpie007** [comment]
mmm, can't this be re-opened?
Installing postman exclusive for the adhoc-backup seems a bit overkill!:)
Another question: is it possible to backup a complete directory instead of defining an array of files?

**Comment by thibmaek** [comment]
I guess you could just pass a directory to the array?
Anyway, my adhoc backup is working perfectly in Home Assistant without using any external REST client like Postman

**Comment by wimpie007** [comment]
could you give an example of your:
hassio_google_backup_adhoc_payload ?
thanks. (i'm looking how you got your config working in your github....)

thnx!

**Comment by thibmaek** [comment]
I have this defined as a secret for the REST payload:

```
'{ "fromPatterns": ["/config/secrets.yaml", "/config/automations.yaml"], "backupDirID": "1e1KkTb..." }'
```
